#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the attended hardware gate for issue #26, candidate 625d5a2.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=17

# ── Bound candidate identity. Changing any of these is a new candidate. ──
CANDIDATE_COMMIT=625d5a22c57d7ab0f792330a3bb7eaa0880f7304
CANDIDATE_TREE=8f3e33a03b1609d2957c63367a4a9c471b6e4ef6
ARCHIVE_SHA256=1eb0a56ca3cff03012884ef7cb7e8dc0c659b8b8db4ccf39d52a0fb75b3a9e5f
SIGNATURE_SHA256=0327309429e43375b02a029efeee7ab5cfbf5242ff0205c03715872769b0e94a
SIGNING_KEY=0B1C5414F8D18F8B6AA78957335FEBC82DB247EC

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="${HIBERMACHY_REPO:-$(cd "$HERE/.." && pwd)}"
CHECKPOINT="$REPO/verification/ticket-26/hibernation-checkpoint.sh"

RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)"
RUN_DIR="$HERE/ticket-26-run-$RUN_ID"
RECORD="$RUN_DIR/evidence-record.md"
STATE_DIR="$RUN_DIR/checkpoints"
BASELINE="$RUN_DIR/baseline"

# Consecutive-cycle count. AC5: any unexplained anomaly restarts this at zero.
CONSECUTIVE=0
ANOMALIES=0

# ── Recording helpers ─────────────────────────────────────────────────────
# Evidence is appended as it is observed, never buffered to the end, so an
# interrupted run still leaves the record of everything already seen.

rec() { printf '%s\n' "$*" >> "$RECORD"; }

# row "Item" "RESULT" "evidence" — one line of a markdown results table.
row() {
  printf '| %s | %s | %s |\n' "$1" "$2" "${3//|/\\|}" >> "$RECORD"
  case $2 in
    PASS)    printf '  %s✓ %s%s — %s\n' "$GREEN"  "$1" "$RESET" "$2" ;;
    FAIL)    printf '  %s✗ %s%s — %s\n' "$RED"    "$1" "$RESET" "$2" ;;
    *)       printf '  %s· %s%s — %s\n' "$DIM"    "$1" "$RESET" "$2" ;;
  esac
}

# ask_result VAR "Item" — the operator records PASS, FAIL or NOT RUN.
# There is no default and blank is not accepted: a blank must never read as a
# pass. This is the project's standing rule, and three candidates were
# invalidated for inferred completion records.
ask_result() {
  local __var=$1 item=$2 reply=""
  while true; do
    printf '  %s%s%s\n' "$BOLD" "$item" "$RESET"
    printf '  %sp%s = PASS   %sf%s = FAIL   %sn%s = NOT RUN  ' \
      "$GREEN" "$RESET" "$RED" "$RESET" "$DIM" "$RESET"
    read -r reply || true
    case ${reply,,} in
      p|pass)     printf -v "$__var" '%s' PASS;    return 0 ;;
      f|fail)     printf -v "$__var" '%s' FAIL;    return 0 ;;
      n|notrun|'not run') printf -v "$__var" '%s' 'NOT RUN'; return 0 ;;
      *) warn "Answer p, f or n. A blank entry never counts as a pass." ;;
    esac
  done
}

# note_evidence "prompt" -> echoes a sanitized free-text observation.
# The operator is reminded not to paste identifiers; the record is publishable.
ask_evidence() {
  local __var=$1 prompt=$2 input=""
  printf '  %s%s%s\n' "$BOLD" "$prompt" "$RESET"
  note 'Sanitize: no hostnames, usernames, boot/session IDs, serials or raw journal text.'
  printf '  > '
  read -r input || true
  printf -v "$__var" '%s' "${input:-none recorded}"
}

# anomaly "what happened" — AC5. Investigation first, then the count restarts.
anomaly() {
  ANOMALIES=$((ANOMALIES + 1))
  CONSECUTIVE=0
  warn "ANOMALY: $1"
  say 'AC5: an unexplained anomaly blocks promotion and restarts the'
  say 'consecutive-cycle count at zero, only after investigation.'
  local cause=""
  ask_evidence cause 'Record the investigation and cause (sanitized):'
  rec ""
  rec "> **Anomaly $ANOMALIES.** $1"
  rec ">"
  rec "> Investigation: $cause"
  rec ">"
  rec "> Consecutive-cycle count restarted at zero."
  rec ""
  say "Consecutive cycle count is now 0."
  pause 'Press Enter to continue.'
}

# ── Live product surface (read-only) ──────────────────────────────────────
# The real IPC target and the real callable names, as declared in
# plugin/Service.qml:1521-1537. Nothing here mutates or sleeps.

# Reach the plugin through omarchy-shell, the documented Quattro seam. A bare
# `quickshell ipc call` cannot locate the running shell: Omarchy starts it as
# `quickshell -n -p /usr/share/omarchy/shell` and there is no default config
# path, so the bare form exits non-zero no matter how healthy the plugin is.
hb_status_raw() { omarchy-shell dev.hibermachy status 2>/dev/null || true; }

# quickshell reports failures on stdout, not stderr, so "non-empty" is not
# evidence that a capture succeeded. Only valid JSON is.
is_json() { [[ -s $1 ]] && python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$1" 2>/dev/null; }

# hb_field NAME — one field from the status snapshot, or a marker.
hb_field() {
  hb_status_raw | python3 -c '
import json, sys
try:
    doc = json.load(sys.stdin)
except Exception:
    print("<status-unavailable>"); raise SystemExit(0)
value = doc.get(sys.argv[1], "<absent>")
print(json.dumps(value) if isinstance(value, (dict, list)) else value)
' "$1" 2>/dev/null || printf '<status-unavailable>'
}

# hb_last_reason — reasonCode of the most recent outcome in history.
hb_last_reason() {
  hb_status_raw | python3 -c '
import json, sys
try:
    doc = json.load(sys.stdin)
except Exception:
    print("<status-unavailable>"); raise SystemExit(0)
history = doc.get("outcomeHistory") or []
print(history[-1].get("reasonCode", "<absent>") if history else "<empty-history>")
' 2>/dev/null || printf '<status-unavailable>'
}

show_status() {
  local auto manual stay inhib rearm hero
  auto=$(hb_field automaticBlockerReasonCode)
  manual=$(hb_field manualBlockerReasonCode)
  stay=$(hb_field stayAwake)
  inhib=$(hb_field compositorIdleInhibited)
  rearm=$(hb_field rearmRequired)
  hero=$(hb_field heroStatus)
  note "heroStatus=$hero  stayAwake=$stay  compositorIdleInhibited=$inhib"
  note "rearmRequired=$rearm"
  note "automaticBlockerReasonCode=$auto"
  note "manualBlockerReasonCode=$manual"
  note "lastOutcomeReasonCode=$(hb_last_reason)"
}

# ── A behavioural case that must NOT sleep ────────────────────────────────
# expect_reason CASE EXPECTED_CODE FIELD — records observed versus expected.
suppression_case() {
  local case_name=$1 expected=$2 field=$3
  local observed result detail
  observed=$(hb_field "$field")
  say "Expected $field: $expected"
  say "Observed $field: $observed"
  show_status
  if [[ $observed == "$expected" ]]; then
    note 'Observed code matches the expected code.'
  else
    warn 'Observed code does NOT match. Record FAIL unless you can explain it.'
  fi
  ask_result result "$case_name"
  ask_evidence detail 'Observation (what you saw, and that no sleep occurred):'
  row "$case_name" "$result" "expected=$expected observed=$observed; $detail"
  [[ $result == FAIL ]] && anomaly "$case_name failed"
  return 0
}

# ── One physical staged-sleep / hibernate / resume cycle ──────────────────
# The wizard never triggers sleep. The operator does, through the real
# product journey, and this records what the operator externally observed.
physical_cycle() {
  local label=$1 origin=$2

  say "Cycle: $origin"
  printf '\n'
  step 'Taking the external pre-sleep checkpoint now.'
  if ! "$CHECKPOINT" record "$label" "$STATE_DIR"; then
    warn 'Checkpoint could not be recorded. Do not proceed with this cycle.'
    row "Cycle $label ($origin)" 'NOT RUN' 'external pre-sleep checkpoint failed'
    return 1
  fi
  printf '\n'
  warn 'From here the machine will really sleep. Save anything still open.'
  pause 'Press Enter when you are ready to begin the cycle.'

  _clear
  printf '\n%s%s▸ Cycle %s in progress · %s%s\n\n' "$BOLD" "$BLUE" "$label" "$origin" "$RESET"
  say 'Now do the following, then come back to this terminal after resume:'
  printf '\n'
  return 0
}

# finish_cycle LABEL ORIGIN — runs after the operator has resumed.
finish_cycle() {
  local label=$1 origin=$2
  local verify_status verify_out observed_down result detail

  printf '\n'
  step 'Verifying the external checkpoint survived into this same session.'
  set +e
  verify_out=$("$CHECKPOINT" verify "$label" "$STATE_DIR" 2>&1)
  verify_status=$?
  set -e
  printf '%s\n' "$verify_out" | sed 's/^/  /'
  printf '\n'

  say 'AC4 requires evidence the product cannot supply for itself:'
  note 'A Hibermachy "Completed" result and free-form journal text cannot'
  note 'certify hibernation. Your own observation is what does.'
  printf '\n'
  if confirm 'Did you SEE the machine fully powered down (screen dark, no fans, no power LED)?'; then
    observed_down=yes
  else
    observed_down=no
    warn 'Without an external powered-down observation this cycle cannot'
    warn 'certify hibernation, however clean the checkpoint looks.'
  fi

  local checkpoint_verdict
  case $verify_status in
    0) checkpoint_verdict='CONFIRMED same-session restoration' ;;
    1) checkpoint_verdict='BROKEN - session did not survive' ;;
    2) checkpoint_verdict='INDETERMINATE - no real sleep interval' ;;
    *) checkpoint_verdict='ERROR running checkpoint' ;;
  esac
  say "External checkpoint: $checkpoint_verdict"
  say "Hibermachy last reason code: $(hb_last_reason)"

  printf '\n'
  ask_result result "Cycle $label ($origin)"
  ask_evidence detail 'Sanitized corroborating observation:'

  # A cycle only counts when all four AC4 legs hold together.
  if [[ $result == PASS && $verify_status -eq 0 && $observed_down == yes ]]; then
    CONSECUTIVE=$((CONSECUTIVE + 1))
    row "Cycle $label ($origin)" PASS \
      "checkpoint=CONFIRMED; powered-down observed=yes; $detail"
    say "Consecutive successful cycles: $CONSECUTIVE of 3"
  else
    local recorded=$result operator_note=""
    if [[ $result == PASS ]]; then
      # Do not let an operator PASS stand as the recorded result when the
      # evidence contradicts it. Keep both facts in the record.
      recorded=FAIL
      operator_note="operator entered PASS, but a required AC4 leg is missing; "
      warn 'You marked PASS but a required leg of AC4 is missing. This cycle'
      warn 'is recorded FAIL and does not count toward the three cycles.'
    fi
    row "Cycle $label ($origin)" "$recorded" \
      "${operator_note}checkpoint=$checkpoint_verdict; powered-down observed=$observed_down; $detail"
    anomaly "Cycle $label ($origin) did not satisfy every AC4 leg"
  fi
  pause 'Press Enter to continue.'
}

# ══════════════════════════════════════════════════════════════════════════

mkdir -p "$RUN_DIR" "$STATE_DIR" "$BASELINE"

banner "Hibermachy attended hardware gate — candidate 625d5a2"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Bind the candidate, and state what this run does not claim"

say "Issue #26, requirement HBR-REQ-075. Candidate commit:"
note "$CANDIDATE_COMMIT"
printf '\n'
say 'Three criteria of issue #25 were resolved by owner determination rather'
say 'than by evidence. They are carried forward, not re-argued, and they'
say 'constrain what this release may ever claim:'
printf '\n'
note 'AC2  no clean environment exists; accepted unmet.'
note '     Never describe this release as clean-room qualified.'
note 'AC5  assistive technology is OUT OF SCOPE; accepted unmet.'
note '     Never describe this release as accessible or screen-reader tested.'
note 'AC7  independent review was met by owner determination, by an agent'
note '     and not a human. Never describe it as security certified.'
printf '\n'
say 'Recording these as accepted-unmet lets this run proceed without'
say 'inventing a pass for any of them.'
printf '\n'

if [[ ! -d $REPO/.git && ! -f $REPO/.git ]]; then
  warn "Not a git repository: $REPO"
  warn 'Set HIBERMACHY_REPO to the candidate checkout and re-run.'
  exit 1
fi

# The external checkpoint tool is tracked in the repository, on the ticket-26
# branch. Fail here with an explanation rather than part-way through a cycle.
if [[ ! -x $CHECKPOINT ]]; then
  warn "External checkpoint tool not found: $CHECKPOINT"
  warn 'AC4 cannot be satisfied without it. Check out the ticket-26 branch,'
  warn 'or point HIBERMACHY_REPO at a checkout that contains it, then re-run.'
  exit 1
fi

identity_ok=yes
actual_commit=$(git -C "$REPO" rev-parse --verify "${CANDIDATE_COMMIT}^{commit}" 2>/dev/null || echo missing)
actual_tree=$(git -C "$REPO" rev-parse "${CANDIDATE_COMMIT}^{tree}" 2>/dev/null || echo missing)
actual_archive=$(git -C "$REPO" archive --format=tar --prefix=hibermachy-helper-0.1.0/ \
                   "$CANDIDATE_COMMIT" 2>/dev/null | gzip -n -9 | sha256sum | awk '{print $1}' \
                 || echo missing)

[[ $actual_commit  == "$CANDIDATE_COMMIT" ]] || identity_ok=no
[[ $actual_tree    == "$CANDIDATE_TREE"   ]] || identity_ok=no
[[ $actual_archive == "$ARCHIVE_SHA256"   ]] || identity_ok=no

say "commit  $actual_commit"
say "tree    $actual_tree"
say "archive $actual_archive"
if [[ $identity_ok != yes ]]; then
  printf '\n'
  warn 'Candidate identity does NOT match the bound values.'
  warn 'AC7: changed bits are a different candidate. Stop, and cut a new one.'
  exit 1
fi
say 'Candidate identity matches the bound values.'

# Fixtures would silently turn this whole gate into a simulation.
printf '\n'
fixture_leak=no
for var in HBR_TEST_MODE HBR_LIFECYCLE_TEST_MODE HBR_TEST_CLOCK_START_MS \
           HBR_CONTRACT_PROBE HBR_POLICY_HELPER_PATH HBR_POLICY_HELPER_LAUNCHER \
           HBR_EFFECTIVE_POLICY_READER; do
  if [[ -n ${!var:-} ]]; then warn "$var is set in this environment"; fixture_leak=yes; fi
done
while IFS='=' read -r name _; do
  [[ $name == HIBERMACHY_SIM_* ]] || continue
  warn "$name is set in this environment"; fixture_leak=yes
done < <(env)
if [[ $fixture_leak == yes ]]; then
  printf '\n'
  warn 'Test fixtures or simulation variables are active.'
  warn 'This gate would measure fixtures, not hardware, and any pass'
  warn 'it produced would be worthless. Clear them and re-run.'
  exit 1
fi
say 'No test-mode or simulation variables are set; the real surface is live.'

mkdir -p "$RUN_DIR"
rec "# Hibermachy attended hardware gate — sanitized evidence record"
rec ""
rec "**Issue:** #26 (attended hardware gate and promotion), HBR-REQ-075"
rec "**Disposition:** in progress; no gate is passed until this record says so"
rec "**Candidate commit:** \`$CANDIDATE_COMMIT\`"
rec "**Candidate tree:** \`$CANDIDATE_TREE\`"
rec "**Source archive SHA-256:** \`$ARCHIVE_SHA256\`"
rec "**Signing fingerprint:** \`$SIGNING_KEY\`"
rec "**Run started (UTC):** $RUN_ID"
rec ""
rec "## Determinations carried forward from issue #25"
rec ""
rec "These were resolved by owner determination, not by evidence. They are"
rec "recorded as accepted-unmet and constrain every claim about this release."
rec ""
rec "| Criterion | Determination |"
rec "| --- | --- |"
rec "| AC2 clean environment | accepted unmet; no clean environment exists |"
rec "| AC5 accessibility | assistive technology out of scope; accepted unmet |"
rec "| AC7 independent review | met by owner determination; agent, not human |"
rec ""
rec "This release is not clean-room qualified, not accessibility certified,"
rec "not security certified, and claims no general version or hardware support."
rec ""
rec "## Candidate identity"
rec ""
rec "| Item | Result | Evidence |"
rec "| --- | --- | --- |"
row 'Candidate commit, tree and archive digest' PASS \
  "commit/tree/archive matched the bound values"
row 'Test fixtures and simulation variables absent' PASS \
  'no HBR_TEST_MODE, HBR_LIFECYCLE_TEST_MODE or HIBERMACHY_SIM_* set'

pause 'Press Enter to confirm the machine.'

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Confirm the designated machine and record the environment"

say 'The gate runs on ONE designated battery-equipped machine with'
say 'independently known-working suspend and hibernation, operator present.'
printf '\n'

os_name=$(. /etc/os-release 2>/dev/null && printf '%s' "${PRETTY_NAME:-unknown}")
kernel=$(uname -r)
has_battery=no; has_ac=no
for bat in /sys/class/power_supply/*; do
  [[ -r $bat/type ]] || continue
  case $(<"$bat/type") in
    Battery) has_battery=yes ;;
    Mains)   has_ac=yes ;;
  esac
done
pkgver() {
  local version
  version=$(pacman -Q "$1" 2>/dev/null | awk '{print $2}')
  printf '%s' "${version:-not installed}"
}

say "OS          $os_name"
say "Kernel      $kernel"
say "Omarchy     $(pkgver omarchy)"
say "Quickshell  $(pkgver quickshell)"
say "systemd     $(pkgver systemd)"
say "Battery     $has_battery        AC adapter  $has_ac"
printf '\n'

if [[ $has_battery != yes ]]; then
  warn 'No battery detected. The AC-deferral cycle of AC2 cannot be run here.'
  warn 'This is not the designated machine.'
  confirm 'Continue anyway, recording the AC-deferral cycle as NOT RUN?' || exit 1
fi

confirm 'Is this the designated machine, with you physically present?' || {
  say 'Stopping. Run this on the designated machine.'; exit 1; }

rec ""
rec "## Environment (sanitized)"
rec ""
rec "| Item | Value |"
rec "| --- | --- |"
rec "| OS | $os_name |"
rec "| Kernel | $kernel |"
rec "| Omarchy | $(pkgver omarchy) |"
rec "| Quickshell | $(pkgver quickshell) |"
rec "| systemd | $(pkgver systemd) |"
rec "| Battery present | $has_battery |"
rec "| AC adapter present | $has_ac |"
rec ""
rec "Recorded as a verified environment only for this exact version"
rec "combination. This is test evidence, not a promise of compatibility,"
rec "maintenance or support on any other combination."

pause 'Press Enter for the hibernation pre-flight.'

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Hibernation pre-flight — this stage never sleeps"

say 'AC1 requires that capability detection never itself triggers sleep.'
say 'Every check below is a read or a D-Bus query. None can initiate sleep.'
printf '\n'

rec ""
rec "## Hibernation pre-flight (non-sleeping)"
rec ""
rec "| Check | Result | Evidence |"
rec "| --- | --- | --- |"

states=$(cat /sys/power/state 2>/dev/null || echo '')
if [[ $states == *disk* ]]; then
  row 'Kernel supports hibernation' PASS "/sys/power/state = $states"
else
  row 'Kernel supports hibernation' FAIL "/sys/power/state = $states"
  warn 'This kernel cannot hibernate. The gate cannot pass here.'
fi

resume_dev=$(cat /sys/power/resume 2>/dev/null || echo '')
resume_off=$(cat /sys/power/resume_offset 2>/dev/null || echo '')
if [[ -n $resume_dev && $resume_dev != 0:0 ]]; then
  row 'Resume device configured' PASS "resume=$resume_dev offset=$resume_off"
else
  row 'Resume device configured' FAIL "resume=$resume_dev"
  warn 'No resume device. A hibernation image could be written but never'
  warn 'restored, which loses the session. Do not run the cycles.'
fi

# Hibernation writes its image to the swap area named by resume=, so zram
# sitting at a higher priority does not capture it. Priority still gets
# recorded, because zram plus hibernation is a common source of trouble.
swap_table=$(awk 'NR>1 {printf "%s(prio %s, %s kB free of %s) ", $1, $5, $3-$4, $3}' /proc/swaps)
image_limit=$(cat /sys/power/image_size 2>/dev/null || echo unknown)
resume_swap_free=$(awk '/^SwapFree:/ {print $2}' /proc/meminfo)
row 'Swap topology' 'NOT RUN' "$swap_table"
row 'Hibernation image size limit' 'NOT RUN' "${image_limit} bytes; SwapFree ${resume_swap_free} kB"

for m in CanHibernate CanSuspend CanSuspendThenHibernate; do
  # Output is: s "yes" — take field 2 and strip the quotes. Do not use
  # `tr -d s`, which would also eat the s in "yes".
  answer=$(busctl call org.freedesktop.login1 /org/freedesktop/login1 \
             org.freedesktop.login1.Manager "$m" 2>/dev/null \
             | awk '{gsub(/"/, "", $2); print $2}' || true)
  answer=${answer:-unavailable}
  if [[ $answer == yes ]]; then
    row "logind $m" PASS "$answer (read-only query; no sleep initiated)"
  else
    row "logind $m" FAIL "$answer"
  fi
done

# A distribution drop-in sets SYSTEMD_SLEEP_FREEZE_USER_SESSIONS=false on the
# sleep units. systemd warns this can misbehave specifically during
# suspend-then-hibernate, which is the exact unit staged sleep uses. It is
# vendor-owned configuration: record it, never change it.
# No match is the normal case and grep exits 1 for it; without `|| true`
# pipefail would abort the whole run here.
freeze_files=$(grep -rls 'SYSTEMD_SLEEP_FREEZE_USER_SESSIONS' \
                 /usr/lib/systemd /etc/systemd 2>/dev/null | tr '\n' ' ' || true)
if [[ -n $freeze_files ]]; then
  row 'User-session freeze overridden by vendor drop-in' 'NOT RUN' \
    "SYSTEMD_SLEEP_FREEZE_USER_SESSIONS set by: $freeze_files"
  printf '\n'
  warn 'A vendor drop-in disables user-session freezing on the sleep units.'
  warn 'systemd warns this can misbehave during suspend-then-hibernate,'
  warn 'which is the unit staged sleep uses. It is recorded as an'
  warn 'environment condition. Do NOT change it: that would mutate system'
  warn 'sleep policy and invalidate the run.'
  printf '\n'
else
  row 'User-session freeze overridden by vendor drop-in' 'NOT RUN' 'no override found'
fi

# suspend-then-hibernate is the staged-sleep unit. Whether it has ever run
# here decides how much weight past hibernations actually carry.
if journalctl -u systemd-suspend-then-hibernate.service -n 1 --no-pager 2>/dev/null \
     | grep -q 'No entries'; then
  row 'Staged-sleep unit previously exercised here' 'NOT RUN' \
    'systemd-suspend-then-hibernate.service has never run on this machine'
  warn 'The staged-sleep unit has never run here. Past direct hibernations'
  warn 'corroborate the hardware, but not this path. Treat a first-cycle'
  warn 'failure as a configuration question before a product question.'
else
  row 'Staged-sleep unit previously exercised here' 'NOT RUN' \
    'systemd-suspend-then-hibernate.service has prior journal entries'
fi

printf '\n'
say 'Pre-flight complete. No sleep was initiated by any check above.'
pause 'Press Enter to capture initial state.'

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Capture initial policy and configuration"

say 'AC1 requires initial policy and configuration to be recorded, and AC5'
say 'requires them verified restored afterwards. Capturing the baseline now.'
printf '\n'

rec ""
rec "## Initial state (AC1)"
rec ""
rec "| Check | Result | Evidence |"
rec "| --- | --- | --- |"

systemd-analyze cat-config systemd/sleep.conf  > "$BASELINE/sleep.conf.txt"  2>&1 || true
systemd-analyze cat-config systemd/logind.conf > "$BASELINE/logind.conf.txt" 2>&1 || true
hb_status_raw > "$BASELINE/hibermachy-status.json" 2>/dev/null || true
( cd "$REPO" && ./lifecycle/status status ) > "$BASELINE/lifecycle-status.json" 2>/dev/null || true
cat /proc/swaps > "$BASELINE/swaps.txt" 2>/dev/null || true

for f in sleep.conf logind.conf; do
  if [[ -s $BASELINE/$f.txt ]]; then
    row "Initial $f captured" PASS "$(wc -l < "$BASELINE/$f.txt") lines baselined"
  else
    row "Initial $f captured" 'NOT RUN' 'could not read effective configuration'
  fi
done
if is_json "$BASELINE/hibermachy-status.json"; then
  row 'Initial Hibermachy status snapshot captured' PASS 'IPC status baselined as valid JSON'
else
  row 'Initial Hibermachy status snapshot captured' 'NOT RUN' \
    'IPC target dev.hibermachy did not answer; is the plugin active?'
  warn 'The plugin did not answer on dev.hibermachy. The behavioural cases'
  warn 'below need it. Activate it before continuing, or record them NOT RUN.'
fi
if is_json "$BASELINE/lifecycle-status.json"; then
  row 'Initial lifecycle inventory captured' PASS 'lifecycle inventory baselined as valid JSON'
else
  row 'Initial lifecycle inventory captured' 'NOT RUN' 'lifecycle status unavailable or not JSON'
fi

say "Baseline written to: ${BASELINE/#$HOME/\~}"
pause 'Press Enter to arm the procedure.'

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Save your work, then explicitly arm"

warn 'Everything after this point can really suspend and hibernate.'
printf '\n'
say 'Before arming:'
step 'Save every open document and commit or stash any work in progress.'
step 'Close anything sensitive you would not want left on screen at resume.'
step 'Make sure you can physically reach the power button and the charger.'
printf '\n'
say 'AC1 requires an explicit arm after this warning. Capability detection'
say 'has already run and never slept the machine; arming is a separate act.'
printf '\n'

readonly ARM_PHRASE='ARMED BY OPERATOR: work saved; designated machine confirmed; real sleep authorized'
say 'Type this line exactly to arm:'
printf '\n  %s%s%s\n\n' "$BOLD" "$ARM_PHRASE" "$RESET"
printf '  > '
read -r arm_input || true
if [[ $arm_input != "$ARM_PHRASE" ]]; then
  printf '\n'
  warn 'That did not match. The procedure is NOT armed and will stop here.'
  rec ""
  rec "## Arm"
  rec ""
  rec "| Item | Result | Evidence |"
  rec "| --- | --- | --- |"
  row 'Explicit operator arm' 'NOT RUN' 'arm phrase not entered; run stopped before any sleep'
  rec ""
  rec "**Final decision:** BLOCKED — the procedure was never armed."
  printf '\n'
  say "Partial record: ${RECORD/#$HOME/\~}"
  exit 1
fi
ARMED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
rec ""
rec "## Arm"
rec ""
rec "| Item | Result | Evidence |"
rec "| --- | --- | --- |"
row 'Save-work warning acknowledged' PASS 'operator warned before arming'
row 'Non-sleeping capability detection confirmed' PASS \
  'pre-flight completed in stage 3 without initiating sleep'
row 'Explicit operator arm' PASS "exact arm phrase entered at $ARMED_AT UTC"
printf '\n'
say "Armed at $ARMED_AT UTC."
pause 'Press Enter to begin the separate behavioural cases.'

rec ""
rec "## Separate attended cases (AC3)"
rec ""
rec "These do not count toward the three consecutive cycles."
rec ""
rec "| Case | Result | Evidence |"
rec "| --- | --- | --- |"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Case 1 of 7 — Stay Awake suppresses automatic staged sleep"

say 'Automatic staged sleep must be suppressed while Stay Awake is on.'
say 'No sleep may occur in this case.'
printf '\n'
step 'Turn Stay Awake ON from the Omarchy menu (Super+Space).'
pause 'Press Enter once Stay Awake is on.'
printf '\n'
suppression_case 'Stay Awake suppression' 'HBR-STAY-AWAKE-ENABLED' automaticBlockerReasonCode
printf '\n'
step 'Turn Stay Awake back OFF before continuing.'
pause 'Press Enter once Stay Awake is off.'

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Case 2 of 7 — a compositor idle inhibitor suppresses automatic sleep"

say 'A Wayland idle inhibitor must suppress automatic staged sleep, while a'
say 'separately confirmed manual request may still bypass it.'
printf '\n'
step 'Start something that holds a compositor idle inhibitor.'
note 'Playing a video full-screen in a browser is the usual way.'
pause 'Press Enter once the inhibitor is active.'
printf '\n'
suppression_case 'Compositor idle inhibition' 'HBR-COMPOSITOR-IDLE-INHIBITED' automaticBlockerReasonCode
printf '\n'
step 'Stop the inhibitor before continuing.'
pause 'Press Enter once it is released.'

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Case 3 of 7 — a system sleep inhibitor refuses a manual request"

say 'Manual staged sleep bypasses Stay Awake and compositor inhibition, but'
say 'it must still honour a system (logind) sleep inhibitor and be REFUSED.'
printf '\n'
say 'In another terminal, hold a system sleep inhibitor:'
printf '\n  %ssystemd-inhibit --what=sleep --why="hibermachy gate" sleep 600%s\n\n' "$BOLD" "$RESET"
pause 'Press Enter once the inhibitor is held.'
printf '\n'
say 'Now request manual staged sleep. It must be refused, not honoured:'
printf '\n  %somarchy-shell dev.hibermachy requestStagedSleep%s\n\n' "$BOLD" "$RESET"
note 'Expected receipt: kind="refused", reasonCode="HBR-SLEEP-SYSTEM-INHIBITED"'
note 'The machine must NOT sleep.'
pause 'Run it, then press Enter.'
printf '\n'
show_status
manual_block=$(hb_field manualBlockerReasonCode)
say "manualBlockerReasonCode = $manual_block"
ask_result r_inhibit 'System-inhibitor refusal'
ask_evidence d_inhibit 'Receipt kind and reason code you saw (and that no sleep occurred):'
row 'System-inhibitor refusal' "$r_inhibit" \
  "expected refused/HBR-SLEEP-SYSTEM-INHIBITED; manualBlockerReasonCode=$manual_block; $d_inhibit"
[[ $r_inhibit == FAIL ]] && anomaly 'System-inhibitor refusal failed'
printf '\n'
step 'Release the system inhibitor (Ctrl-C the systemd-inhibit command).'
pause 'Press Enter once released.'

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Case 4 of 7 — fresh activity is required to re-arm"

say 'After activation, reload, a relevant policy change, or a prior staged'
say 'sleep, automatic staged sleep must wait for NEW activity before it can'
say 'run again. It must not fire off a stale idle observation.'
printf '\n'
rearm=$(hb_field rearmRequired)
fresh=$(hb_field freshActivityObserved)
say "rearmRequired        = $rearm"
say "freshActivityObserved = $fresh"
say "automaticBlockerReasonCode = $(hb_field automaticBlockerReasonCode)"
note 'Expected while waiting to re-arm: HBR-FRESH-ACTIVITY-REQUIRED'
printf '\n'
step 'Move the mouse or press a key to produce fresh activity, then re-check.'
pause 'Press Enter after producing activity.'
say "rearmRequired is now        = $(hb_field rearmRequired)"
say "freshActivityObserved is now = $(hb_field freshActivityObserved)"
printf '\n'
ask_result r_rearm 'Fresh-activity re-arm'
ask_evidence d_rearm 'What the re-arm fields did before and after activity:'
row 'Fresh-activity re-arm' "$r_rearm" "$d_rearm"
[[ $r_rearm == FAIL ]] && anomaly 'Fresh-activity re-arm failed'

# ── Stage 10 ──────────────────────────────────────────────────────────────
stage "Case 5 of 7 — reload while latched"

say 'Reloading the plugin while it is latched must not replay a request,'
say 'must not restore a countdown, and must not keep a stale capability or'
say 'inhibitor snapshot. It fails closed and demands fresh activity again.'
printf '\n'
warn 'This case has NO merge-gate coverage for the same-boot path.'
note 'The same-boot reload reason code HBR-SLEEP-SERVICE-RECREATED is'
note 'present in the source but no automated test exercises it. This'
note 'attended run is its first and only exercise, so look carefully.'
printf '\n'
step 'Reload or disable-and-re-enable the Hibermachy plugin.'
pause 'Press Enter once the plugin has come back.'
printf '\n'
show_status
say "Last outcome reason code: $(hb_last_reason)"
note 'Expect rearmRequired=true after reload, and no replayed request.'
printf '\n'
ask_result r_reload 'Reload while latched'
ask_evidence d_reload 'Reason code and re-arm state after reload:'
row 'Reload while latched' "$r_reload" "no merge-gate coverage for same-boot path; $d_reload"
[[ $r_reload == FAIL ]] && anomaly 'Reload while latched failed'

# ── Stage 11 ──────────────────────────────────────────────────────────────
stage "Case 6 of 7 — deliberate fallback to ordinary suspend"

say 'When hibernation is unavailable but suspend is executable, a manual'
say 'request must fall back to ordinary suspend, say so in the confirmation,'
say 'and must NOT claim hibernation in its result.'
printf '\n'
say "fallbackAvailable = $(hb_field fallbackAvailable)"
say "heroStatus        = $(hb_field heroStatus)"
printf '\n'
note 'Expected on fallback: selectedMode="suspend", outcome "Degraded",'
note 'reasonCode "HBR-SLEEP-SUSPEND-FALLBACK". The confirmation text must'
note 'name ordinary suspend.'
printf '\n'
warn 'Reaching this state on real hardware needs hibernation to be genuinely'
warn 'unexecutable. Do NOT mutate system sleep policy or swap to force it.'
warn 'If you cannot reach it without mutating policy, record NOT RUN.'
printf '\n'
ask_result r_fallback 'Deliberate suspend fallback'
ask_evidence d_fallback 'Confirmation wording and result, or why NOT RUN:'
row 'Deliberate suspend fallback' "$r_fallback" "$d_fallback"
[[ $r_fallback == FAIL ]] && anomaly 'Deliberate suspend fallback failed'

# ── Stage 12 ──────────────────────────────────────────────────────────────
stage "Case 7 of 7 — early wake during the suspended interval"

say 'Waking during the suspended interval, before the hibernate delay'
say 'elapses, must not produce an invented hibernation claim. The latch'
say 'stays set until fresh activity.'
printf '\n'
warn 'This case has NO merge-gate coverage.'
note 'HBR-SLEEP-EARLY-WAKE is enumerated in the source but no automated'
note 'test exercises it. This attended run is its first and only exercise.'
printf '\n'
say 'This case does involve a real suspend, but a deliberately short one.'
step 'Request staged sleep, let the machine suspend, then wake it EARLY,'
step 'well before the hibernate delay would transition it to hibernation.'
pause 'Press Enter when you are back from the early wake.'
printf '\n'
show_status
say "Last outcome reason code: $(hb_last_reason)"
note 'The result must not claim hibernation was confirmed.'
printf '\n'
ask_result r_early 'Early wake'
ask_evidence d_early 'Reason code, and confirmation that no hibernation was claimed:'
row 'Early wake' "$r_early" "no merge-gate coverage; $d_early"
[[ $r_early == FAIL ]] && anomaly 'Early wake failed'

pause 'Press Enter to begin the three consecutive physical cycles.'

rec ""
rec "## Consecutive staged-sleep / hibernation / resume cycles (AC2, AC4)"
rec ""
rec "Each cycle requires all of: an external pre-sleep checkpoint, the typed"
rec "request origin, an external observation of the powered-down state,"
rec "same-session restoration, and sanitized corroboration. A Hibermachy"
rec "Completed result cannot certify hibernation on its own."
rec ""
rec "| Cycle | Result | Evidence |"
rec "| --- | --- | --- |"

# ── Stage 13 ──────────────────────────────────────────────────────────────
stage "Cycle 1 of 3 — automatic request"

if physical_cycle cycle-1 'automatic request after idle expiry'; then
  step 'Make sure Stay Awake is OFF and no idle inhibitor is held.'
  step 'Produce fresh activity, then STOP TOUCHING the machine.'
  step 'Let the idle delay expire so staged sleep starts on its own.'
  step 'Let it suspend, then let the hibernate delay transition it to hibernate.'
  step 'Watch for the machine to power down fully, then power it back on.'
  printf '\n'
  warn 'Do not press any key in this terminal until the machine has resumed.'
  pause 'Press Enter only after the machine has resumed.'
  finish_cycle cycle-1 'automatic request after idle expiry'
else
  warn 'Skipping this cycle: the pre-sleep checkpoint could not be recorded.'
  pause 'Press Enter to continue.'
fi

# ── Stage 14 ──────────────────────────────────────────────────────────────
stage "Cycle 2 of 3 — confirmed manual request"

if physical_cycle cycle-2 'confirmed manual request'; then
  step 'Open the Omarchy menu with Super+Space.'
  step 'Choose "Suspend then Hibernate".'
  step 'Read the confirmation dialog, then confirm it.'
  note 'The confirmation must name the selected mode, the Stay Awake and'
  note 'compositor-inhibitor bypass, and continued system-inhibitor enforcement.'
  step 'Let it suspend, then hibernate. Watch it power down, then power it on.'
  printf '\n'
  pause 'Press Enter only after the machine has resumed.'
  finish_cycle cycle-2 'confirmed manual request'
else
  warn 'Skipping this cycle: the pre-sleep checkpoint could not be recorded.'
  pause 'Press Enter to continue.'
fi

# ── Stage 15 ──────────────────────────────────────────────────────────────
stage "Cycle 3 of 3 — AC deferral, then disconnect"

if [[ $has_battery != yes ]]; then
  warn 'No battery on this machine, so AC deferral cannot be exercised.'
  row 'Cycle cycle-3 (AC deferral then disconnect)' 'NOT RUN' 'no battery present'
else
  if physical_cycle cycle-3 'AC deferral then disconnect'; then
  step 'Connect AC power before starting.'
  step 'Begin staged sleep and let the machine suspend.'
  step 'With AC still connected, confirm it STAYS suspended and does not'
  step '  transition to hibernation while on AC.'
  step 'Now disconnect AC while it is still suspended.'
  step 'Confirm it then transitions to hibernation and powers down.'
  step 'Power it back on.'
  printf '\n'
  note 'AC deferral depends on the requested AC-power behaviour. If system'
  note 'policy was never applied, deferral may simply not be in effect;'
  note 'record what actually happened rather than what was expected.'
  printf '\n'
  pause 'Press Enter only after the machine has resumed.'
  finish_cycle cycle-3 'AC deferral then disconnect'
  else
    warn 'Skipping this cycle: the pre-sleep checkpoint could not be recorded.'
    pause 'Press Enter to continue.'
  fi
fi

rec ""
rec "**Consecutive successful cycles:** $CONSECUTIVE of 3"
rec ""
rec "**Anomalies recorded:** $ANOMALIES"

# ── Stage 16 ──────────────────────────────────────────────────────────────
stage "Restore and verify the initial state"

say 'AC5 requires initial policy and configuration to be verified restored.'
printf '\n'

rec ""
rec "## Restoration (AC5)"
rec ""
rec "| Check | Result | Evidence |"
rec "| --- | --- | --- |"

systemd-analyze cat-config systemd/sleep.conf  > "$RUN_DIR/final-sleep.conf.txt"  2>&1 || true
systemd-analyze cat-config systemd/logind.conf > "$RUN_DIR/final-logind.conf.txt" 2>&1 || true

for f in sleep.conf logind.conf; do
  if [[ ! -s $BASELINE/$f.txt ]]; then
    row "$f restored to initial state" 'NOT RUN' 'no baseline captured'
  elif diff -q "$BASELINE/$f.txt" "$RUN_DIR/final-$f.txt" >/dev/null 2>&1; then
    row "$f restored to initial state" PASS 'byte-identical to the baseline'
  else
    row "$f restored to initial state" FAIL 'differs from the baseline'
    warn "$f differs from the captured baseline. Investigate before promoting."
    diff "$BASELINE/$f.txt" "$RUN_DIR/final-$f.txt" 2>&1 | head -20 | sed 's/^/  /'
    anomaly "$f was not restored to its initial state"
  fi
done

( cd "$REPO" && ./lifecycle/status status ) > "$RUN_DIR/final-lifecycle-status.json" 2>/dev/null || true
if is_json "$BASELINE/lifecycle-status.json" && is_json "$RUN_DIR/final-lifecycle-status.json"; then
  if diff -q "$BASELINE/lifecycle-status.json" "$RUN_DIR/final-lifecycle-status.json" >/dev/null 2>&1; then
    row 'Lifecycle inventory unchanged' PASS 'identical to the baseline'
  else
    row 'Lifecycle inventory unchanged' 'NOT RUN' \
      'differs from baseline; review the diff before promoting'
    warn 'The lifecycle inventory changed during the run. Review it.'
  fi
else
  row 'Lifecycle inventory unchanged' 'NOT RUN' 'baseline or final inventory unavailable'
fi

ask_result r_unrelated 'Unrelated configuration and state untouched'
ask_evidence d_unrelated 'What you checked outside Hibermachy ownership:'
row 'Unrelated configuration and state untouched' "$r_unrelated" "$d_unrelated"

# ── Stage 17 ──────────────────────────────────────────────────────────────
stage "Gate decision and promotion handoff"

# Re-verify identity: promotion is only ever of the unchanged candidate.
final_archive=$(git -C "$REPO" archive --format=tar --prefix=hibermachy-helper-0.1.0/ \
                  "$CANDIDATE_COMMIT" 2>/dev/null | gzip -n -9 | sha256sum | awk '{print $1}' \
                || echo missing)
identity_still_ok=no
[[ $final_archive == "$ARCHIVE_SHA256" ]] && identity_still_ok=yes

# grep -c already prints 0 when nothing matches, and then exits 1, so a
# `|| echo 0` fallback would append a second zero and corrupt the count.
fails=$(grep -c '^| .* | FAIL |' "$RECORD" 2>/dev/null || true)
notruns=$(grep -c '^| .* | NOT RUN |' "$RECORD" 2>/dev/null || true)
fails=${fails:-0}
notruns=${notruns:-0}

rec ""
rec "## Gate decision"
rec ""
rec "| Item | Value |"
rec "| --- | --- |"
rec "| Consecutive successful cycles | $CONSECUTIVE of 3 |"
rec "| Anomalies | $ANOMALIES |"
rec "| Rows marked FAIL | $fails |"
rec "| Rows marked NOT RUN | $notruns |"
rec "| Candidate unchanged at close | $identity_still_ok |"
rec ""

GATE_PASSED=no
if [[ $CONSECUTIVE -ge 3 && $ANOMALIES -eq 0 && $fails -eq 0 && $identity_still_ok == yes ]]; then
  GATE_PASSED=yes
fi

say "Consecutive successful cycles : $CONSECUTIVE of 3"
say "Anomalies                     : $ANOMALIES"
say "Rows marked FAIL              : $fails"
say "Rows marked NOT RUN           : $notruns"
say "Candidate unchanged at close  : $identity_still_ok"
printf '\n'

if [[ $GATE_PASSED == yes ]]; then
  printf '  %s%sHardware gate: PASSED%s\n\n' "$BOLD" "$GREEN" "$RESET"
  rec "**Hardware gate:** PASSED"
  rec ""
  rec "Passed on this exact environment only. This records test evidence and"
  rec "claims no general version support, hardware compatibility, security"
  rec "certification or accessibility certification."
else
  printf '  %s%sHardware gate: BLOCKED%s\n\n' "$BOLD" "$RED" "$RESET"
  rec "**Hardware gate:** BLOCKED"
  rec ""
  rec "Promotion is blocked. Every criterion must hold with no anomaly, no"
  rec "FAIL row, three consecutive cycles, and an unchanged candidate."
  say 'Promotion is blocked. Nothing has been published.'
fi
printf '\n'

rec ""
rec "## Promotion"
rec ""
rec "| Check | Result | Evidence |"
rec "| --- | --- | --- |"
row 'Sanitized verification record published' 'NOT RUN' 'publish step is performed by the release operator'
row 'Unchanged candidate promoted' 'NOT RUN' 'not performed by this procedure'
row 'Public metadata/artifact/checksum/download smoke checks' 'NOT RUN' 'follows promotion'
row 'Lifecycle discovery smoke check' 'NOT RUN' 'follows promotion'
rec ""
rec "**Final decision:** $( [[ $GATE_PASSED == yes ]] \
  && echo 'hardware gate passed; promotion not yet performed' \
  || echo 'BLOCKED — hardware gate did not pass' )"
rec ""
rec "Published artifacts are immutable per version (AC7). A failure creates a"
rec "new candidate identity, and a post-release defect is corrected only in a"
rec "new release, never by replacing a published artifact in place."

_clear
printf '\n%s%s  Attended hardware gate finished%s\n\n' "$BOLD" "$BLUE" "$RESET"
say "Evidence record: ${RECORD/#$HOME/\~}"
say "Checkpoints:     ${STATE_DIR/#$HOME/\~}"
printf '\n'
warn 'This procedure has published NOTHING. It has not pushed, signed,'
warn 'tagged, created a release, or promoted anything.'
printf '\n'

if [[ $GATE_PASSED == yes ]]; then
  say 'The gate passed. Promotion is a separate, deliberate act that you'
  say 'perform by hand, with the finished evidence record in front of you.'
  printf '\n'
  say 'Before you publish anything, re-read the record and confirm:'
  step 'Every row you expected to pass says PASS, and no row says FAIL.'
  step 'Every NOT RUN row is one you consciously accepted.'
  step 'Nothing in the record claims clean-room, accessibility, screen-reader'
  step '  or security qualification.'
  step 'The candidate is still unchanged.'
  printf '\n'
  say 'Promotion, when you choose to do it, is roughly:'
  printf '\n'
  note "  git push origin $CANDIDATE_COMMIT:refs/heads/release-0.1.0"
  note "  gh release create v0.1.0 \\"
  note "    handoff/candidate-625d5a2/hibermachy-helper-0.1.0.tar.gz \\"
  note "    handoff/candidate-625d5a2/hibermachy-helper-0.1.0.tar.gz.sig \\"
  note "    --target release-0.1.0 --prerelease"
  printf '\n'
  warn 'Those commands are one-way. Once 0.1.0 is public with those bytes,'
  warn 'AC7 forbids replacing them: a defect needs a new version entirely.'
  warn 'Check them yourself before running them; do not paste them blind.'
else
  say 'Do not promote. Investigate the blocked rows, fix the cause, and note'
  say 'that changing any shipped bit produces a NEW candidate identity, which'
  say 'requires this whole gate to run again from the beginning.'
fi
printf '\n'
