#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if command -v wslview >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

# The candidate and destination embedded in this historical wizard are obsolete.
printf '%s\n' 'This release wizard is superseded. See handoff/HIBERMACHY-HANDOFF.md for the corrected candidate and current release status.' >&2
exit 1

TOTAL_STAGES=4

readonly ARCHIVE=/tmp/hibermachy-ticket24-prerelease.AzfHL0/hibermachy-helper-0.1.0.tar.gz
readonly SIGNATURE=${ARCHIVE}.sig
readonly EXPECTED_SHA256=dea6a8b56dbff19fe74a6353373a3f013674a4db662fb61c6f0f864a5f229dee
readonly EXPECTED_SHA512=6cee6c5b30ca4f1b0025c4f24cbd52e322a5d35faa0e76a3f3fc675a034366cb43e9f6a653090d92e03824b77c72838744dc991a703890b2e6861daaea8cef00
readonly RELEASE_TAG=v0.1.0
readonly REPOSITORY=hibermachy/hibermachy
readonly RELEASE_BRANCH=release-candidate-v0.1.0

banner "Hibermachy Ticket 24 release signing"

stage "Verify the release archive"
say "This checks that the file still contains the exact frozen candidate."
[[ -f "$ARCHIVE" ]] || { warn "Missing archive: $ARCHIVE"; exit 1; }
actual_sha256=$(sha256sum "$ARCHIVE" | awk '{print $1}')
actual_sha512=$(sha512sum "$ARCHIVE" | awk '{print $1}')
[[ "$actual_sha256" == "$EXPECTED_SHA256" ]] || { warn "SHA-256 mismatch; stop and regenerate the candidate."; exit 1; }
[[ "$actual_sha512" == "$EXPECTED_SHA512" ]] || { warn "SHA-512 mismatch; stop and regenerate the candidate."; exit 1; }
say "Archive verified: $ARCHIVE"
say "SHA-256: $actual_sha256"
say "SHA-512: $actual_sha512"
pause "Press Enter to choose a signing key."

stage "Choose or create your GPG signing key"
say "Your private key stays in GPG. Never paste or upload it."
gpg --list-secret-keys --keyid-format LONG || true
if ! gpg --list-secret-keys --with-colons 2>/dev/null | grep -q '^sec:'; then
  step "No secret key was found. Run: gpg --full-generate-key"
  step "Choose an RSA signing key, at least 3072 bits, and protect it with a passphrase."
  pause "Create the key in another terminal, then press Enter."
fi
ask GPG_FINGERPRINT "Paste the full fingerprint of the key to use:"
normalized_fingerprint=${GPG_FINGERPRINT//[[:space:]]/}
gpg --list-secret-keys "$normalized_fingerprint" >/dev/null 2>&1 || { warn "That secret key is not available in GPG."; exit 1; }
GPG_FINGERPRINT=$(gpg --with-colons --fingerprint "$normalized_fingerprint" | awk -F: '$1 == "fpr" { print $10; exit }')
[[ -n "$GPG_FINGERPRINT" ]] || { warn "Could not resolve the full fingerprint."; exit 1; }
say "Using fingerprint: $GPG_FINGERPRINT"

stage "Create and verify the detached signature"
say "GPG may prompt for your key passphrase."
if [[ -e "$SIGNATURE" ]]; then
  warn "A signature already exists at $SIGNATURE."
  confirm "Replace it with a new signature?" || exit 1
  rm -f -- "$SIGNATURE"
fi
confirm "Sign the verified archive now?" || exit 1
gpg --batch --yes --local-user "$GPG_FINGERPRINT" --output "$SIGNATURE" --detach-sign "$ARCHIVE"
gpg --verify "$SIGNATURE" "$ARCHIVE"
signature_sha256=$(sha256sum "$SIGNATURE" | awk '{print $1}')
signature_sha512=$(sha512sum "$SIGNATURE" | awk '{print $1}')
say "Signature verified: $SIGNATURE"
say "Signature SHA-256: $signature_sha256"
say "Signature SHA-512: $signature_sha512"
pause "Press Enter to publish the prerelease."

stage "Publish the GitHub prerelease"
if ! gh auth status >/dev/null 2>&1; then
  say "GitHub CLI is not currently authenticated."
  step "Run: gh auth login -h github.com"
  step "Choose GitHub.com, SSH for Git operations, and authenticate in your browser."
  pause "Finish login in another terminal, then press Enter."
fi
gh auth status >/dev/null 2>&1 || { warn "GitHub authentication is still unavailable."; exit 1; }
say "The candidate PKGBUILD downloads releases from $REPOSITORY."
say "Your current checkout origin is a personal repository, so publishing there would not satisfy the package contract."
gh repo view "$REPOSITORY" >/dev/null 2>&1 || {
  warn "Your authenticated account cannot access $REPOSITORY."
  warn "Stop here. Either create/get access to that canonical repository or revise the package URL and produce a new candidate."
  exit 1
}
say "This will push the frozen candidate to $REPOSITORY branch $RELEASE_BRANCH."
say "It then creates prerelease $RELEASE_TAG and uploads the archive and detached signature."
confirm "Publish the candidate branch and GitHub prerelease now?" || exit 1
git push "git@github.com:${REPOSITORY}.git" 8e8592b633ebfb25ba8d968541f0affd04a1f142:"refs/heads/$RELEASE_BRANCH"
gh release create "$RELEASE_TAG" "$ARCHIVE" "$SIGNATURE" --repo "$REPOSITORY" --target "$RELEASE_BRANCH" --prerelease --title "Hibermachy 0.1.0 prerelease" --notes "Ticket 24 candidate prerelease. Candidate commit: 8e8592b633ebfb25ba8d968541f0affd04a1f142."
archive_url="https://github.com/$REPOSITORY/releases/download/$RELEASE_TAG/$(basename "$ARCHIVE")"
signature_url="https://github.com/$REPOSITORY/releases/download/$RELEASE_TAG/$(basename "$SIGNATURE")"
say "Archive URL: $archive_url"
say "Signature URL: $signature_url"
say "Signing-key fingerprint: $GPG_FINGERPRINT"
say "Give those three values to Codex so Ticket 24 can verify and record them."

finish
